# For local development, only database is running
#
# docker compose up -d
# uvicorn app.main:app --reload
#

services:
  postgres_db:
    restart: unless-stopped
    image: postgres:16
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    env_file:
      - .env
    ports:
      - "${PG_PORT}:5432"

volumes:
  postgres_db:
