
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c79b0938ea4b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # -- commands auto generated by Alembic -- ###
    op.create_table(
        "Pets",
        sa.Column("pet_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("place", sa.String(length=256), nullable=False),
        sa.Column("type", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("pet_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### -- commands auto generated by Alembic -- ###
    op.drop_table("pets")
    # ### end Alembic commands ###
